outstanding-oxen/bluebikeshed

package-lock.json, package.json, server/db/db.js, server/db/models/address.js, server/db/models/cart.js, server/db/models/customer.js, server/db/models/index.js
Associations still need to be set!
---
=> Left models have been defined 

server/api/customer.js, server/api/index.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> added address and customer api routes

script/seed.js, server/db/models/order.js
-Edited order to have tax be decimal
-Edited seed file to reflect change in tax
- added one dream
=> Create product seed

script/seed.js, server/db/models/order.js, server/db/models/user.js
Added more seed:
-users (admins and users)
-dream categories
-dreams
-orders
-order details
=> Added more Seed Data

client/app.js, client/components/Footer.js, client/components/Home.js, client/components/ProductPage.js, server/db/db.js
* [] Home Page almost completed
* [] Footer added
* [] Product Page added (defined some grid things) 
---
_Your PR Notes Here_
=> Frontend branch 

.travis.yml
Edited Travis.yml file to create appropriate database
-from boilermaker-test to iDream-test
=> changed database in travis.yml to create proper database

.travis.yml
edited travis yml to update app name and heroku token. 
Should be able to continuously deploy.
=> edited travis yml to update app name and heroku token

client/app.js, client/components/AllProducts.js, client/components/ProductInAllProducts.js, client/components/navbar.js, client/routes.js
=> All products frontend

client/components/ItemOnProductPage.js, client/components/ProductInAllProducts.js, client/components/ProductPage.js
=> Product page

client/store/admin.js, script/seed.js, server/api/customer.js, server/api/order.js
I added more images, so that Ruslan can work on the individual product pages.
Some pages the images are larger than others.
=> added more images

client/components/ItemOnProductPage.js
=> Product page improvments

client/store/cart.js, client/store/index.js, server/api/orders.js, server/api/users.js, server/db/models/index.js
The thunks are based on routes that are not created yet. Once the routes are created it should work (hopefully).
=> Cart reducer

client/store/cart.js
=> Created getOrder thunk & getCart Action. Fixed addToOrder thunk bug

client/store/cart.js
=> Updated getOrder and addToOrder thunks to allow for guest interaction

server/api/orderdetails.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> added post route for order detail

client/components/navbar.js, client/store/index.js
The badge changes the value every time user adds/removes items to/from cart.
=> Now the badge is changed every time the amount of items changes

client/components/navbar.js
-After log in, nav bar shows name and log out
-log out functionality works.
=> Logout branch

server/auth/index.js
=> Updated auth api to include Address with user

client/components/CartPage.js, client/components/ProductInCart.js
added in product images on cart page
*THIS IS A TEMPORARY FIX only for the demo since we are unable to load images through the state*
=> added images in cart page

client/components/ItemOnProductPage.js, client/components/ProductInAllProducts.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> edited description
